In [1]:
import scipy.io as sio
import numpy as np


In [14]:
import torch
a = torch.tensor([[1,2 ,3], [3, 4, 5
                             ]], dtype=torch.float)
torch.clamp(a, 2, 4)

tensor([[2., 2., 3.],
        [3., 4., 4.]])

In [41]:
x = np.array([[1], [2]])
n = 1
err_mean = 10*np.log10(np.mean(np.power(10, np.divide(x.reshape(-1, n), 10)), axis=1))
err_mean

array([1., 2.])

In [23]:
a = np.array([2], dtype=np.str_)
a

array(['2'], dtype='<U1')

In [3]:
folder = "Pz and Sz/Dongyuan/"
files = ["Primary_path.mat", "Secondary_path.mat"]


In [17]:
for file in files:
    mat = sio.loadmat(folder+file)
    variable_names = [key for key in mat.keys() if not key.startswith("__")]
    for key in variable_names:
        print(key)

Pz1
S


In [63]:
pri = sio.loadmat(folder+files[0])
sec = sio.loadmat(folder+files[1])
sec2 = sio.loadmat(folder+savefile)

In [64]:
print(mat["Pz1"].argmax())

print(sec["S"].argmax())
print(sec2["S"].argmax())

255
127
255


In [55]:
zeros = np.zeros((mat["Pz1"].argmax()-sec["S"].argmax(), 1))
sec2 = np.concat([zeros, sec["S"]], axis=0)

In [62]:
savefile = "Secondary_path_0.mat"
sio.savemat(folder+savefile, {"S": sec2},)

In [34]:
arr = np.array([[1, 2, 3]])
zeros = np.array([[0, 0 ]])
np.concat([zeros, arr], axis=1)

array([[0, 0, 1, 2, 3]])